stages:
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - echo API_URL=$API_URL >> .env
  
deploy:
  image: alpine:latest
  when: always
  stage: deploy
  tags:
    - deployment
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
      allow_failure: false
  script:
    - command -v ssh-agent >/dev/null || (apk update && apk add openssh-client)
    - eval $(ssh-agent -s)
    - echo "$ID_RSA" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - scp -o StrictHostKeyChecking=no .env $SERVER_USER@$SERVER_IP:~/yaonpay-frontend/.env
    - |
      ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
      cd ~/yaonpay-frontend &&
      git pull origin main &&
      yarn install --frozen-lockfile &&
      yarn build && 
      pm2 start yarn -- start;
      exit
      "
